### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by ztt0821** [workingcoder/EDCNN#1]
Hi, may I ask how to download the dataset. I have check the website, it's closed https://www.aapm.org/grandchallenge/lowdosect/, and use the link https://doi.org/10.7937/9npb-2637 to search. But I didn't find any dataset

**Comment by workingcoder** [comment]
We download the aapm-mayo dataset from this link: https://www.dropbox.com/sh/txplswleuxgrdue/AABD_1W7-SKdXuZD4myvC2Hqa?dl=0

**Comment by jhkd-kevin** [comment]
@workingcoder Hi, may I ask how to download the dataset, the source link is invalid.
